version: '3.3'
services:
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: 'movelist'
      MYSQL_USER: '*****'
      MYSQL_PASSWORD: '*****'
      MYSQL_ROOT_PASSWORD: '*****'
    ports:
      - '3319:3306'
    expose:
      - '3319'
